import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/footer/footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen ">
        <div className="bg-info-content min-h-screen flex flex-col">
            {/* <Header /> */}
            {children}
            {/* <Footer />               */}
        </div>
      </body>
    </html>
  );
}
